name: Build Container

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: "files"
          MYSQL_USER: "files"
          MYSQL_PASSWORD: "files"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ':dockerCreateDockerfile'
        env:
          FILES_DB_HOST: "mysql"
          FILES_DB_PORT: 3306
          FILES_DB_DATABASE: "files"
          FILES_DB_USER: "files"
          FILES_DB_PASSWORD: "files"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/perpheads/ph-files
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: server/build
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}